scalar DateTime

type Query {
    getAll: [PromotionResponse!]!
    getById(id: ID!): PromotionResponse!
}

type Mutation {
    create(request: PromotionRequest!): PromotionResponse!
    update(id: ID!, request: PromotionRequest!): PromotionResponse!
    delete(id: ID!): Boolean!
}

# Input for mutations
input PromotionRequest {
    code: String!
    description: String
    expiredDate: DateTime
    giveAwayDay: DateTime
    discountPercent: Int
    archivedMiles: Float
    plusMiles: Float
    quantity: Float
}

# Output of query and mutation
type PromotionResponse {
    id: ID!
    code: String!
    description: String
    expiredDate: DateTime
    giveAwayDay: DateTime
    discountPercent: Int
    archivedMiles: Float
    plusMiles: Float
    quantity: Float
    createdBy: String
    createdAt: Float
    lastUpdatedBy: String
    lastUpdatedAt: Float
}